package internal

import (
	"bytes"
	"text/template"
)

var sshConfigTemplate = template.Must(template.New("ssh_config").Parse(`# The configuration is generated by xs with the config file: {{ .ConfigFile }}

{{range $i, $host := .Hosts -}}
Host {{$host.Name}}{{range $ii, $param := $host.SortedSSHConfig}}{{range $k, $v := $param}}
    {{$k}} {{$v}}{{end}}{{end}}

{{end -}}`))

func genSSHConfig(cfg *Config) ([]byte, error) {
	input := map[string]interface{}{
		"ConfigFile": cfg.Filepath,
		"Hosts":      cfg.Hosts,
	}
	var b bytes.Buffer
	if err := sshConfigTemplate.Execute(&b, input); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}
