package internal

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestGenSSHConfig(t *testing.T) {
	cfg := &Config{
		Filepath: "path/to/config",
		Hosts: []*Host{
			{
				Name: "host1",
				SSHConfig: map[string]string{
					"User":     "user1",
					"Port":     "22",
					"HostName": "host1.example.com",
				},
			},
			{
				Name: "host2",
				SSHConfig: map[string]string{
					"User":     "user2",
					"Port":     "22",
					"HostName": "host2.example.com",
				},
			},
		},
	}
	b, err := genSSHConfig(cfg)
	assert.NoError(t, err)
	assert.Equal(t, `# The configuration is generated by xs with the config file: path/to/config

Host host1
    HostName host1.example.com
    Port 22
    User user1

Host host2
    HostName host2.example.com
    Port 22
    User user2

`, string(b))
	// t.Logf("ssh config:\n%s", string(b))

}
